name: Home School Hero
favicon: null
layout_spectrum: 0.11767200101166964
typography_spectrum: 0.424656922230497
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.5097301125060767
  lightness: 0.36569968215189874
  saturation: 0.5694995992816985
  rhythmicContrast: 0.9787156130187213
purpose: []
